In [1]:
from google_images_search import GoogleImagesSearch
import curses

# Configura tu API Key y CX (Custom Search Engine ID)
api_key = 'AIzaSyBdC_ol-yZGKMf4kaaQKioImBRChTJMh0w'
cx = 'f17ae98bd36e043fa'

# Crea una instancia de GoogleImagesSearch
gis = GoogleImagesSearch(api_key, cx)

# Realiza una búsqueda de imágenes
search_params = {
    'q': 'gatos',  # Término de búsqueda (en este caso, "gatos")
    'num': 100,       # Número de imágenes a descargar
    'safe': 'medium',  # Nivel de seguridad ('high', 'medium', 'off')
}

gis.search(search_params=search_params)

# Guarda las imágenes en memoria
images = []
for image in gis.results():
    images.append(image)
print(len(images))




100


In [3]:
import threading        # Manejo de hilos
from time import sleep  # Pausar tiempos
import random           # Números aleatorios
import numpy as np
from google_images_search import GoogleImagesSearch
import curses

# Guarda las imágenes en memoria
#images = np.empty(100)
images = []
# Configura tu API Key y CX (Custom Search Engine ID)
api_key = 'AIzaSyBdC_ol-yZGKMf4kaaQKioImBRChTJMh0w'
cx = 'f17ae98bd36e043fa'

# Crea una instancia de GoogleImagesSearch
gis = GoogleImagesSearch(api_key, cx)

def ejecutar():
    print(f'Comienza {threading.current_thread().name}')
    # Realiza una búsqueda de imágenes
    search_params = {
        'q': 'gatos',  # Término de búsqueda (en este caso, "gatos")
        'num': 10,       # Número de imágenes a descargar
        'safe': 'medium',  # Nivel de seguridad ('high', 'medium', 'off')
    }
    gis.search(search_params=search_params)
    for image in gis.results():
        #images[aux] = image
        #aux = aux+1
        images.append(image)

    print(f'Termina {threading.current_thread().name}')
    comprobarCantidad()

def comprobarCantidad():
    if len(images) < 500:
        ejecutar()
    else:
        return

# Crear los hilos

hilo1 = threading.Thread(target=ejecutar, name='Hilo 1')
hilo2 = threading.Thread(target=ejecutar, name='Hilo 2')
hilo3 = threading.Thread(target=ejecutar, name='Hilo 3')
hilo4 = threading.Thread(target=ejecutar, name='Hilo 4')
hilo5 = threading.Thread(target=ejecutar, name='Hilo 5')
hilo6 = threading.Thread(target=ejecutar, name='Hilo 6')
hilo7 = threading.Thread(target=ejecutar, name='Hilo 7')
hilo8 = threading.Thread(target=ejecutar, name='Hilo 8')
hilo9 = threading.Thread(target=ejecutar, name='Hilo 9')
hilo10 = threading.Thread(target=ejecutar, name='Hilo 10')

# Ejecutar los hilos
hilo1.start()
hilo1.join()
hilo2.start()
hilo2.join()
hilo3.start()
hilo3.join()
hilo4.start()
hilo4.join()
hilo5.start()
hilo5.join()
hilo6.start()
hilo6.join()
hilo7.start()
hilo7.join()
hilo8.start()
hilo8.join()
hilo9.start()
hilo9.join()
hilo10.start()
hilo10.join()
# Esperar a que terminen los hilos ejecutados
hilo1.join()
hilo2.join()
hilo3.join()
hilo4.join()
hilo5.join()
hilo6.join()
hilo7.join()
hilo8.join()
hilo9.join()
hilo10.join


print(len(images))
# Ejecutar los hilos secuencialmente
#hilo4.start()
#hilo4.join()
#hilo5.start()
#hilo5.join()
#hilo6.start()
#hilo6.join()

print('El hilo principal sí espera por el resto de hilos.')

Comienza Hilo 1
Termina Hilo 1
Comienza Hilo 1
Termina Hilo 1
Comienza Hilo 1
Termina Hilo 1
Comienza Hilo 1
Termina Hilo 1
Comienza Hilo 1
Termina Hilo 1
Comienza Hilo 1
Termina Hilo 1
Comienza Hilo 1
Termina Hilo 1
Comienza Hilo 1


In [7]:
import numpy as np
kernel2 = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 1, -1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
])
print(kernel2)

kernel3 = np.array([
    [0, 0, 1, 0, 0],
    [0, 0, 3, 0, 0],
    [0, 0, -3, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
])
print(kernel3)

kernel4 = np.array([
    [0, 0, 0, 0, 0],
    [0, -1, 2, -1, 0],
    [0, 2, -4, 2, 0],
    [0, -1, 2, -1, 0],
    [0, 0, 0, 0, 0],
])
print(kernel4)

kernel5 = np.array([
    [0, 0, 0, 0, 0],
    [0, -1, 2, -1, 0],
    [0, 2, -4, 2, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
])
print(kernel5)

kernel6 = np.array([
    [-1, 2, -2, 2, -1],
    [2, -6, 8, -6, 2],
    [-2, 8, -12, 8, -2],
    [2, -6, 8, -6, 2],
    [-1, 2, -2, 2, -1],
])
print(kernel6)

kernel7 = np.array([
    [-1, 2, -2, 2, -1],
    [2, -6, 8, -6, 2],
    [-2, 8, -12, 8, -2],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
])
print(kernel7)

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  1 -1  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[[ 0  0  1  0  0]
 [ 0  0  3  0  0]
 [ 0  0 -3  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[[ 0  0  0  0  0]
 [ 0 -1  2 -1  0]
 [ 0  2 -4  2  0]
 [ 0 -1  2 -1  0]
 [ 0  0  0  0  0]]
[[ 0  0  0  0  0]
 [ 0 -1  2 -1  0]
 [ 0  2 -4  2  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[[ -1   2  -2   2  -1]
 [  2  -6   8  -6   2]
 [ -2   8 -12   8  -2]
 [  2  -6   8  -6   2]
 [ -1   2  -2   2  -1]]
[[ -1   2  -2   2  -1]
 [  2  -6   8  -6   2]
 [ -2   8 -12   8  -2]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]


In [6]:
pip install windows-curses

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


DEPRECATION: google-images-search 1.4.6 has a non-standard dependency specifier click>=7.0<=8.1.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of google-images-search or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [1]:
from google_images_search import GoogleImagesSearch
from threading import Thread
import queue
import requests
from PIL import Image
from io import BytesIO

api_key = 'AIzaSyBdC_ol-yZGKMf4kaaQKioImBRChTJMh0w'
cx = 'f17ae98bd36e043fa'
gis = GoogleImagesSearch(api_key, cx)

def cargar_imagenes(q, imagenes):
    while True:
        try:
            search_params = q.get(timeout=3)  # Espera 3 segundos o hasta que haya un elemento en la cola
        except queue.Empty:
            break  # Si no hay elementos durante 3 segundos, el hilo termina

        # Realiza la búsqueda
        gis.search(search_params=search_params)
        for image in gis.results():
            # Obtiene la URL de la imagen y la carga en memoria
            response = requests.get(image.url)
            img = Image.open(BytesIO(response.content))
            imagenes.append(img)

# Cola para almacenar los parámetros de búsqueda
search_queue = queue.Queue()

# Lista para almacenar las imágenes cargadas
imagenes_en_memoria = []

# Cargar la cola con los parámetros de búsqueda
for i in range(50):
    search_params = {
        'q': 'término de búsqueda',  # Modifica esto según lo que quieras buscar
        'num': 1
    }
    search_queue.put(search_params)

# Crear y comenzar los hilos
threads = []
for i in range(10):
    thread = Thread(target=cargar_imagenes, args=(search_queue, imagenes_en_memoria))
    thread.start()
    threads.append(thread)

# Esperar a que todos los hilos terminen
for thread in threads:
    thread.join()

print(f"Se han cargado {len(imagenes_en_memoria)} imágenes en memoria.")


Exception in thread Thread-6 (cargar_imagenes):
Traceback (most recent call last):
  File "c:\Program Files\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "c:\Program Files\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nicoe\AppData\Local\Temp\ipykernel_18360\2634261915.py", line 20, in cargar_imagenes
  File "C:\Users\nicoe\AppData\Roaming\Python\Python312\site-packages\google_images_search\fetch_resize_save.py", line 151, in search
    self._search_images(*self._get_data())
  File "C:\Users\nicoe\AppData\Roaming\Python\Python312\site-packages\google_images_search\fetch_resize_save.py", line 178, in _search_images
    for url, referrer_url in self._google_custom_search.search(
  File "C:\Users\nicoe\AppData\Roaming\Python\Python312\site-packages\google_images_search\google_api.py", line 83, in search
    res = self._query_google_api(search_params, cache_discovery)
          ^^^^^^^^^^^^^^

Se han cargado 16 imágenes en memoria.
